### PR TITLE
Comment samba tasks

### PR DESCRIPTION
**Pull request by kshithijiyer**
Problem:
Samba requires glusterfs-api however due to patch [1] where we have added libgfapi0 to fix issue [2], we are seeing issue like [3] while trying to run centosci on patches.

Fix:
Comment samba tasks present in setup-glusto.yml

Links:
[1] #101
[2] gluster/glusterfs#1297
[3] https://ci.centos.org/job/gluster_glusto-patch-check/2220/console

### CODE REVIEW

**Comment by kshithijiyer** [comment]
@deepshikhaaa Could you please review and merge this patch?

**Comment by deepshikhaaa** [comment]
Why it is not required?

**Comment by balakreddy** [comment]
> Why it is not required?

Currently, the Installation of samba packages is failing so he commented, other tests which have to run on glusterfs also failing as the due to samba installation issue. Once it is fixed, will revert back.

**Comment by deepshikhaaa** [comment]
But, can we root cause the issue on samba failure first? Or is there any bz opened on the same. Doing this would affect the samba based test suite, no?

**Comment by balakreddy** [comment]
> But, can we root cause the issue on samba failure first? Or is there any bz opened on the same. Doing this would affect the samba based test suite, no?

Agree, currently, we have to unblock the current tests on glusterfs protocol.
That is the reason to comment out samba.
will fix the issues based on gluster/glusterfs#1297 in the subsequent patches.

**Comment by deepshikhaaa** [comment]
Can you please mention the samba failures on the same issue. Need someone from samba to take a look.

**Comment by anoopcs9** [comment]
> Can you please mention the samba failures on the same issue. Need someone from samba to take a look.

@balakreddy 
With Kaleb's [patch](https://review.gluster.org/#/c/glusterfs/+/24563/) merged, I don't expect any more failures during installation of samba packages.

**Pull request merged**
