### PR TITLE
Update default branch name

### PR DESCRIPTION
**Pull request by anoopcs9**

### CODE REVIEW

**Review by kshithijiyer — APPROVED** [review]
LGTM

**Comment by anoopcs9** [comment]
@kshithijiyer Oops.. I deleted the merge branch thinking that it got into _main_ branch. I am re-opening the pull request

**Comment by kshithijiyer** [comment]
> @kshithijiyer Oops.. I deleted the merge branch thinking that it got into _main_ branch. I am re-opening the pull request

No issues

**Review by kshithijiyer — APPROVED** [review]

**Comment by obnoxxx** [comment]
@anoopcs9 - sorry, I hadn't seen that you had this PR up already - I have fixed this as #143 ...  Should have checked PRs first.

**Pull request closed without merging**
