### PR TITLE
Add gd2-nightly-rpms job

### PR DESCRIPTION
**Pull request by kshlm**
Depends on gluster/glusterd2#775

### CODE REVIEW

**Comment by kshlm** [comment]
@nigelbabu Apart from running createrepo_c and pushing the artifacts, is there anything else required to setup a nightly repo?

**Comment by nigelbabu** [comment]
This is pretty much it. I would argue that you don't want to create the repo file every single time, but it's better to handle all of this in one script than in several scripts

**Comment by kshlm** [comment]
I just adapted what I saw in the nightly-gluster rpms job. But I agree. We don't actually need to be creating the repo each time. This basically replaces the existing repo on the artifacts server each time. If we could run stuff on the artifacts server, maybe we could update the repo database on it, instead of replacing it. But since we can't this is the best we can do, I guess.

**Comment by kshlm** [comment]
@nigelbabu Can this be merged and the new job created?

**Comment by nigelbabu** [comment]
Done! There was a small mistake which I've now corrected.

**Pull request merged**
